name: 'ChangeLogAutomation Action'
description: 'GitHub action to process changelog file.'
inputs:
  input:
    description: 'Input changelog file'
    required: true
    default: './CHANGELOG.md'
  format:
    description: 'Output file format: either Markdown of PlainText'
    required: true
    default: 'Markdown'
  output:
    description: 'Output file path'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
  post-if: 'success()'
